

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "login": "admin",
    "password": "Admin@123"
}

###
GET http://localhost:3000/professional
# Content-Type: application/json

# {
#     "cpf": "08223712946",
#     "name": "Geovanni Magnani",
#     "phone": "11987654321",
#     "password": "409834",
#     "email": "magnanigeovanni@gmail.com",
#     "userType": "ADMIN"
# }